### ISSUE TITLE
What if entry has múltiple object classes

### ISSUE THREAD

**Issue by JorgeMerchan** [ucsf-iam/UcsfLdapOrm#1]
Hello, I am a user of Gorg and Im switching to ucsf, have you seen the use case where when persisting a new entry to the LDAP, it requires more than one objectclass, For example a custom object class and inetorgperson.
Can the annotation ObjectClass receive en arrary o coma separated string instead of a single string like: ObjectClass('inetOrgPerson,CustomObjectClass') or ObjectClass(['inetOrgPerson,CustomObjectClass'])

**Comment by ucsf-iam** [comment]
Hello Jorge,

Yes you can. For example,  at UCSF we have a custom ucsfEduPerson object class (an extension of the InetOrgPerson).  When I persist it, I set the UcsfEduPerson::objectClass value to an array which includes 'ucsfEduPerson' along with two other non-ancestor/non-descendent object class names. 

If you look at the Ucsf\LdapOrmBundle\Entity\Ldap\LdapEntity class, which represents the object class of 'top', you'll see that the LdapEntity::objectClass member variable is annotated with @arrayField(). This designates the variable as representing a multi-value LDAP attribute -- as is objectClass in LDAP. When creating a new LdapEntity (sub)class instance, just call LdapEntity::setObjectClass() with an array parameter comprised of whatever number of object class names you wish. I have also overridden getObjectClass() and setObjectClass() in extensions of LdapEntity to provide custom behavior for handling the object class value.  Note that the default value is set within LdapEntity's constructor.

Jason Gabler
Programmer/Analyst
Identity & Access Management - UCSF IT
